export type Product = {
  id: string
  name: string
  brand: string
  price: number
  oldPrice?: number
  discount?: number
  image: string
  category: string
  tag?: "2x1" | "Oferta" | "Nuevo"
  stock?: number
  description?: string
  benefits?: string[]
  usage?: string
  sku?: string
}

export const categories = [
  { name: "Especial 2x1", highlight: true },
  { name: "Medicamentos" },
  { name: "Dermocosmética" },
  { name: "Vitaminas" },
  { name: "Bebés" },
  { name: "Higiene Personal" },
  { name: "Cuidado Personal" },
  { name: "Belleza" },
  { name: "Perfumería" },
  { name: "Adultos Mayores" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Protector Solar FPS 50 Facial Toque Seco 50ml",
    brand: "ISDIN",
    price: 18999,
    oldPrice: 26999,
    discount: 30,
    image: "/products/protector-solar.png",
    category: "Dermocosmética",
    tag: "Oferta",
    stock: 12,
    sku: "ISDIN-PS50-001",
    description: "Protector solar de alta protección con fórmula de toque seco. Ideal para uso diario en pieles mixtas o grasas. No deja sensación grasosa ni brillos. Protección UVA y UVB certificada dermatológicamente.",
    benefits: ["FPS 50+ protección alta", "Toque seco, sin brillo", "Textura ultraligera", "Resistente al sudor"],
    usage: "Aplicar generosamente 20 minutos antes de la exposición solar. Reaplicar cada 2 horas.",
  },
  {
    id: "2",
    name: "Crema Facial Hidratante Antioxidante 50ml",
    brand: "Neutrogena",
    price: 14499,
    oldPrice: 18999,
    discount: 24,
    image: "/products/crema-facial.png",
    category: "Dermocosmética",
    stock: 8,
    sku: "NEU-CF-002",
    description: "Crema hidratante con antioxidantes que protege y nutre la piel durante todo el día. Textura ligera de rápida absorción. Libre de aceite, testada dermatológicamente.",
    benefits: ["Hidratación 24 horas", "Fórmula antioxidante", "Sin aceite, no comedogénica", "Apta pieles sensibles"],
    usage: "Aplicar mañana y noche sobre la piel limpia. Masajear suavemente hasta absorber completamente.",
  },
  {
    id: "3",
    name: "Shampoo Reparación Total 5 Acciones 400ml",
    brand: "L'Oréal Elvive",
    price: 6299,
    image: "/products/shampoo.png",
    category: "Cuidado Personal",
    tag: "2x1",
    stock: 30,
    sku: "LOREAL-SH-003",
    description: "Shampoo con 5 acciones reparadoras para cabello dañado. Fórmula con keratina y ceramidas que restaura la fibra capilar desde adentro. Cabello suave, fuerte y brillante.",
    benefits: ["5 acciones reparadoras", "Con keratina y ceramidas", "Cabello 2x más fuerte", "Brillo intenso"],
    usage: "Aplicar sobre cabello mojado, masajear el cuero cabelludo y enjuagar. Repetir si es necesario.",
  },
  {
    id: "4",
    name: "Vitamina C 1000mg Efervescente x30 sobres",
    brand: "Redoxon",
    price: 9899,
    oldPrice: 12499,
    discount: 20,
    image: "/products/vitaminas.png",
    category: "Vitaminas",
    tag: "2x1",
    stock: 22,
    sku: "RED-VC1000-004",
    description: "Vitamina C efervescente de alta concentración. Refuerza el sistema inmunológico, actúa como antioxidante y ayuda en la absorción de hierro. Sabor naranja.",
    benefits: ["1000mg de Vitamina C pura", "Refuerza la inmunidad", "Antioxidante potente", "Sabor naranja natural"],
    usage: "Disolver un sobre en un vaso de agua. Consumir preferiblemente con las comidas.",
  },
  {
    id: "5",
    name: "Pañales Ultra Comfort Talle G x52 unidades",
    brand: "Pampers",
    price: 23499,
    oldPrice: 28999,
    discount: 19,
    image: "/products/pañales.png",
    category: "Bebés",
    tag: "Oferta",
    stock: 20,
    sku: "PAM-PG-005",
    description: "Pañales Ultra Comfort con capa ultra absorbente y protección de 12 horas. Diseño suave y flexible que se adapta a los movimientos del bebé. Con indicador de humedad.",
    benefits: ["Absorción 12 horas", "Indicador de humedad", "Diseño ultra flexible", "Sin latex, hipoalergénico"],
    usage: "Cambiar el pañal frecuentemente. Limpiar bien la zona antes de colocar uno nuevo.",
  },
  {
    id: "6",
    name: "Labial Líquido Mate Súper Stay 16hs",
    brand: "Maybelline",
    price: 8999,
    image: "/products/labial.png",
    category: "Belleza",
    tag: "Nuevo",
    stock: 19,
    sku: "MAY-LM-006",
    description: "Labial líquido de larga duración con fórmula cómoda y ligera. Hasta 16 horas de color intenso sin resecado. Disponible en 12 tonos intensos.",
    benefits: ["16 horas de duración", "Fórmula no resecante", "Color ultra pigmentado", "12 tonos disponibles"],
    usage: "Aplicar desde el centro hacia los bordes de los labios. Dejar secar 30 segundos.",
  },
  {
    id: "7",
    name: "212 NYC Eau de Parfum Feminino 90ml",
    brand: "Carolina Herrera",
    price: 64999,
    oldPrice: 79999,
    discount: 18,
    image: "/products/perfume.png",
    category: "Perfumería",
    stock: 6,
    sku: "CH-212-007",
    description: "Fragancia fresca y sofisticada, símbolo de la energía y dinamismo de Nueva York. Notas de cidra, gardenia y almizcle para una mujer moderna y segura.",
    benefits: ["Aroma duradero 8+ horas", "Frasco coleccionable", "Notas cítricas y florales", "Icono de la moda mundial"],
    usage: "Aplicar en puntos de pulso: muñecas, cuello y detrás de las orejas. Guardar alejado de la luz solar directa.",
  },
  {
    id: "8",
    name: "Alcohol en Gel Antibacterial 250ml",
    brand: "Buchi Farma",
    price: 2899,
    image: "/products/alcohol-gel.png",
    category: "Higiene Personal",
    tag: "2x1",
    stock: 50,
    sku: "BF-AG-008",
    description: "Gel antibacterial con 70% de alcohol isopropílico. Elimina el 99.9% de bacterias sin necesidad de enjuague. Con aloe vera para cuidar la piel.",
    benefits: ["70% alcohol isopropílico", "Elimina 99.9% de bacterias", "Con aloe vera hidratante", "Sin enjuague necesario"],
    usage: "Aplicar una cantidad adecuada en la palma de la mano. Friccionar hasta que se absorba completamente.",
  },
  {
    id: "9",
    name: "Ibuprofeno 400mg x20 comprimidos",
    brand: "Ibupirac",
    price: 3499,
    image: "/products/alcohol-gel.png",
    category: "Medicamentos",
    stock: 45,
    sku: "IBU-400-009",
    description: "Antiinflamatorio no esteroide (AINE) para el tratamiento del dolor leve a moderado, fiebre e inflamación. Comprimidos recubiertos de acción rápida.",
    benefits: ["Acción rápida en 30 min", "Anti-inflamatorio potente", "Analgésico y antipirético", "Cubierta que protege el estómago"],
    usage: "Adultos: 1 comprimido cada 6-8 horas. No superar 3 comprimidos por día. Tomar con comida.",
  },
  {
    id: "10",
    name: "Omeprazol 20mg x14 cápsulas",
    brand: "Omesec",
    price: 4299,
    image: "/products/alcohol-gel.png",
    category: "Medicamentos",
    stock: 35,
    sku: "OMP-20-010",
    description: "Inhibidor de la bomba de protones para el tratamiento de úlcera gástrica, gastritis y reflujo gastroesofágico. Alivio en 24-48 horas.",
    benefits: ["Alivia el reflujo en 24hs", "Protege la mucosa gástrica", "Una sola dosis diaria", "Alta tolerancia"],
    usage: "Una cápsula al día, preferentemente en ayunas, 30 minutos antes del desayuno. Consultar médico.",
  },
  {
    id: "11",
    name: "Paracetamol 500mg x20 comprimidos",
    brand: "Tafirol",
    price: 2199,
    image: "/products/alcohol-gel.png",
    category: "Medicamentos",
    stock: 60,
    sku: "PAR-500-011",
    description: "Analgésico y antipirético de amplio uso. Eficaz para dolores de cabeza, musculares, dentales y fiebre. Alta tolerabilidad gástrica.",
    benefits: ["Sin irritación gástrica", "Acción analgésica rápida", "Antipirético eficaz", "Apto embarazadas (consultar)"],
    usage: "1-2 comprimidos cada 4-6 horas. Máximo 8 comprimidos por día. No superar dosis recomendada.",
  },
  {
    id: "12",
    name: "Vitamina D3 2000UI + K2 x60 cápsulas",
    brand: "Nature's Plus",
    price: 12499,
    oldPrice: 15999,
    discount: 22,
    image: "/products/vitaminas.png",
    category: "Vitaminas",
    stock: 14,
    sku: "NP-D3K2-012",
    description: "Vitamina D3 con K2 para optimizar la absorción de calcio. Apoya la salud ósea, el sistema inmune y el equilibrio del calcio en el organismo.",
    benefits: ["2000UI de Vitamina D3", "K2 para absorción de calcio", "Salud ósea y muscular", "Refuerzo inmunológico"],
    usage: "1 cápsula al día con el desayuno. Almacenar en lugar fresco y seco.",
  },
  {
    id: "13",
    name: "Omega 3 1000mg Alta Potencia x60 cápsulas",
    brand: "NOW Foods",
    price: 16999,
    oldPrice: 21999,
    discount: 22,
    image: "/products/vitaminas.png",
    category: "Vitaminas",
    tag: "Oferta",
    stock: 11,
    sku: "NOW-O3-013",
    description: "Ácidos grasos Omega 3 de alta concentración con EPA y DHA de origen marino. Beneficios para el corazón, el cerebro, las articulaciones y la piel.",
    benefits: ["Alta concentración EPA/DHA", "Salud cardiovascular", "Función cerebral", "Anti-inflamatorio natural"],
    usage: "2 cápsulas al día con las comidas. Guardar refrigerado una vez abierto.",
  },
  {
    id: "14",
    name: "Multivitamínico Complete Adultos x60 comprimidos",
    brand: "Centrum",
    price: 18499,
    oldPrice: 23999,
    discount: 23,
    image: "/products/vitaminas.png",
    category: "Vitaminas",
    stock: 9,
    sku: "CTR-MV-014",
    description: "Multivitamínico completo con 30 vitaminas y minerales esenciales. Fórmula científicamente diseñada para adultos. Apoya la energía, el sistema inmune y el metabolismo.",
    benefits: ["30 vitaminas y minerales", "Apoya la energía diaria", "Refuerzo inmunológico", "Sin gluten ni lactosa"],
    usage: "1 comprimido al día con el desayuno. No exceder la dosis recomendada.",
  },
  {
    id: "15",
    name: "Melatonina 5mg Liberación Gradual x30 comp",
    brand: "Natrol",
    price: 8999,
    image: "/products/vitaminas.png",
    category: "Vitaminas",
    tag: "Nuevo",
    stock: 16,
    sku: "NAT-MEL-015",
    description: "Melatonina de liberación gradual para regular el ciclo sueño-vigilia. Ayuda a conciliar el sueño de forma natural, sin efectos secundarios ni dependencia.",
    benefits: ["Conciliación natural del sueño", "Sin efecto sedante residual", "No genera dependencia", "Regula el ritmo circadiano"],
    usage: "1 comprimido 30 minutos antes de acostarse. No manejar maquinaria después de tomarlo.",
  },
  {
    id: "16",
    name: "Crema Corporal Nutritiva Karité 400ml",
    brand: "Nivea",
    price: 7499,
    oldPrice: 9999,
    discount: 25,
    image: "/products/crema-facial.png",
    category: "Cuidado Personal",
    stock: 15,
    sku: "NIV-CC-016",
    description: "Crema corporal con manteca de karité y pro-vitaminas. Hidratación profunda de larga duración. Piel suave, nutrida y protegida por hasta 48 horas.",
    benefits: ["Hidratación 48 horas", "Manteca de karité", "Piel ultra suave", "Absorción rápida"],
    usage: "Aplicar sobre la piel limpia y seca. Masajear suavemente hasta absorber. Usar mañana y noche.",
  },
  {
    id: "17",
    name: "Desodorante Clinical Extra Dry 48hs 48g",
    brand: "Dove",
    price: 5499,
    oldPrice: 6999,
    discount: 21,
    image: "/products/alcohol-gel.png",
    category: "Higiene Personal",
    stock: 18,
    sku: "DOV-DC-017",
    description: "Desodorante con protección clínica de 48 horas. Fórmula dermatológicamente testeada con moisturizers activos. Protección máxima contra el sudor y el olor.",
    benefits: ["Protección 48 horas", "Dermatológicamente testeado", "Con moisturizers activos", "Libre de alcohol"],
    usage: "Aplicar sobre la axila limpia y seca. Una sola aplicación brinda protección de 48 horas.",
  },
  {
    id: "18",
    name: "Pasta Dental Blanqueadora Luminous White 90g",
    brand: "Colgate",
    price: 3299,
    image: "/products/alcohol-gel.png",
    category: "Higiene Personal",
    stock: 40,
    sku: "COL-PT-018",
    description: "Pasta dental blanqueadora con micropartículas que eliminan manchas superficiales. Protección contra caries y sarro. Dientes notablemente más blancos en 2 semanas.",
    benefits: ["Blanquea en 2 semanas", "Micropartículas blanqueadoras", "Protección anticaries", "Aliento fresco 12hs"],
    usage: "Cepillar durante al menos 2 minutos, dos veces al día. Escupir y enjuagar.",
  },
  {
    id: "19",
    name: "Talco para Bebés Clásico Johnson's 200g",
    brand: "Johnson's Baby",
    price: 4299,
    image: "/products/pañales.png",
    category: "Bebés",
    stock: 30,
    sku: "JB-TB-019",
    description: "Talco suave para bebé con fórmula hipoalergénica y dermatológicamente testeada. Mantiene la piel del bebé fresca, suave y protegida. Fragancia suave característico.",
    benefits: ["Fórmula hipoalergénica", "Dermatológicamente testeado", "Piel fresca y seca", "Aroma suave"],
    usage: "Aplicar una pequeña cantidad en la palma de la mano y luego en la piel del bebé. Evitar el área de la cara.",
  },
  {
    id: "20",
    name: "Crema Hidratante para Bebés Stelatopia 200ml",
    brand: "Mustela",
    price: 8999,
    oldPrice: 10999,
    discount: 18,
    image: "/products/pañales.png",
    category: "Bebés",
    stock: 12,
    sku: "MUS-CH-020",
    description: "Crema hidratante especialmente formulada para pieles sensibles y atópicas del bebé. Sin parabenos, sin fragancia. Testada en pieles atópicas.",
    benefits: ["Libre de parabenos", "Sin fragancia agregada", "Pieles sensibles y atópicas", "Ingredientes naturales"],
    usage: "Aplicar generosamente en todo el cuerpo. Masajear suavemente hasta absorber. Usar tantas veces como sea necesario.",
  },
  {
    id: "21",
    name: "Calcigenol Calcio + Vitamina D3 x60 comp",
    brand: "Calcigenol",
    price: 15999,
    oldPrice: 19999,
    discount: 20,
    image: "/products/vitaminas.png",
    category: "Adultos Mayores",
    stock: 13,
    sku: "CALC-D-021",
    description: "Suplemento de calcio con vitamina D3 para la salud ósea. Previene la osteoporosis y mejora la densidad mineral ósea. Especialmente recomendado para adultos mayores.",
    benefits: ["Previene la osteoporosis", "Vitamina D para absorción", "Alta biodisponibilidad", "Formato fácil de tomar"],
    usage: "1 comprimido dos veces al día con las comidas. Consultar con su médico para dosificación personalizada.",
  },
  {
    id: "22",
    name: "Ginkgo Biloba 120mg Concentrado x60 cápsulas",
    brand: "Nature's Way",
    price: 11999,
    image: "/products/vitaminas.png",
    category: "Adultos Mayores",
    stock: 17,
    sku: "NW-GINK-022",
    description: "Extracto estandarizado de Ginkgo Biloba para mejorar la circulación cerebral y la memoria. Contiene 24% de flavonoides glucósidos y 6% de terpenos.",
    benefits: ["Mejora la circulación cerebral", "Apoya la memoria y concentración", "Extracto estandarizado", "Antioxidante natural"],
    usage: "1 cápsula dos veces al día con las comidas. Los resultados se aprecian después de 4-6 semanas de uso continuo.",
  },
  {
    id: "23",
    name: "Sérum Vitamina C 10% Antimanchas 30ml",
    brand: "Vichy",
    price: 22499,
    oldPrice: 28999,
    discount: 22,
    image: "/products/crema-facial.png",
    category: "Dermocosmética",
    tag: "Nuevo",
    stock: 7,
    sku: "VCH-VC10-023",
    description: "Sérum antioxidante con vitamina C pura al 10% más vitamina E y ácido salicílico. Ilumina el tono, reduce manchas y unifica la piel. Fórmula dermatológica.",
    benefits: ["10% Vitamina C pura", "Reduce manchas visiblemente", "Ilumina el tono de la piel", "Fórmula anti-envejecimiento"],
    usage: "Aplicar 3-4 gotas sobre la piel limpia, antes de la crema hidratante. Usar por la mañana. Siempre acompañar con FPS.",
  },
  {
    id: "24",
    name: "Protector Solar Corporal FPS 50 Sport 200ml",
    brand: "Banana Boat",
    price: 12999,
    oldPrice: 15999,
    discount: 19,
    image: "/products/protector-solar.png",
    category: "Dermocosmética",
    stock: 20,
    sku: "BB-PSC-024",
    description: "Protección solar corporal FPS 50 resistente al agua y al sudor. Ideal para actividades deportivas y días de playa. Fórmula ligera, no grasosa.",
    benefits: ["FPS 50 protección alta", "Resistente al agua", "Fórmula sport", "Larga duración"],
    usage: "Aplicar generosamente 20 minutos antes de la exposición solar. Reaplicar cada 2 horas o después del agua.",
  },
  {
    id: "25",
    name: "Shampoo Sin Sulfatos Cuidado Color 400ml",
    brand: "Elvive",
    price: 7499,
    oldPrice: 9499,
    discount: 21,
    image: "/products/shampoo.png",
    category: "Cuidado Personal",
    tag: "Oferta",
    stock: 22,
    sku: "ELV-SH-025",
    description: "Shampoo sin sulfatos especialmente formulado para cabello teñido o con tratamientos. Protege el color y la estructura del cabello. Con aceite de girasol y ceramidas.",
    benefits: ["Sin sulfatos agresivos", "Protege el color 6 semanas", "Con aceite de girasol", "Para cabello tratado"],
    usage: "Aplicar sobre cabello mojado, masajear y enjuagar. Para mejores resultados usar con acondicionador de la línea.",
  },
]

export function formatPrice(value: number): string {
  return new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    minimumFractionDigits: 0,
  }).format(value)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getProductsByTag(tag: Product["tag"]): Product[] {
  return products.filter((p) => p.tag === tag)
}
